webtest/iti/urls.py
from django.conf.urls import url

from . import views

app_name = 'iti'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^send$', views.send, name='send'),
    url(r'^success$', views.success, name='success'),
    url(r'^history$', views.history, name='history'),
    url(r'^fail$', views.fail, name='fail'),
    url(r'^history/(?P<pk>[0-9]+)', views.transaction, name='transaction'),
    url(r'^del/(?P<pk>[0-9]+)', views.del_trans, name='delete transaction'),
]

webtest/webtest/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^rest/', include('rest.urls')),
    url(r'^digest/', include('digest.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^iti/', include('iti.urls')),
    url(r'^admin/', admin.site.urls),
]

webtest/iti/models.py
from __future__ import unicode_literals

from django.db import models

from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible  # only if you need to support Python 2
class Transaction(models.Model):
    trans_id = models.IntegerField(primary_key=True, blank=True, null=False)
    time = models.DateField(blank=False, null=False, auto_now_add=True)
    email = models.TextField(blank=False, null=False)
    amount = models.TextField(blank=False, null=False)
    cashtype = models.TextField(blank=False, null=False)
    def __str__(self):
        return self.email

webtest/iti/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Transaction
import time

####################
#currency symbols
#also the supported types of currency in /send
#can be saved in database instead
currency_symbol = {'USD':u'$', 'EUR':u'€', 'JPY':u'¥', 'CNY':u'¥'}
####################


def index(request):
    template = loader.get_template('iti/index.html')
    context = {}
    return HttpResponse(template.render(context, request))

def send(request):
    template = loader.get_template('iti/send.html')
    currency_list = currency_symbol.keys()
    currency_list.sort(reverse=True)
    context = {'currency': currency_list}
    return HttpResponse(template.render(context, request))

def success(request):
    #time.sleep(5)
    template = loader.get_template('iti/success.html')
    try:
        transaction = Transaction(email=request.POST['email'],
                                  amount=request.POST['amount'],
                                  cashtype=request.POST['cashtype'])
        transaction.save()
    except:
        return HttpResponseRedirect('/iti/fail')
    print request.POST['cashtype']
    print transaction.amount
    context = {}
    context['amount'] = request.POST['amount']
    context['email'] = request.POST['email']
    return HttpResponse(template.render(context, request))

def fail(request):
    template = loader.get_template('iti/fail.html')
    context = {}
    return HttpResponse(template.render(context, request))

def history(request):
    transactions = Transaction.objects.all()
    tr_history = []
    for i in transactions:
        t=currency_symbol[i.cashtype]
        t += i.amount
        tr_history.append((i.time,i.email,t,i.trans_id))
    template = loader.get_template('iti/history.html')
    context = {'trans' : tr_history}
    return HttpResponse(template.render(context, request))

def transaction(request, pk):
    trans = get_object_or_404(Transaction, trans_id=pk)
    template = loader.get_template('iti/transaction.html')
    context = {}
    t=currency_symbol[trans.cashtype] 
    context['amount'] = t+trans.amount
    context['email'] = trans.email
    context['date'] = trans.time
    context['trans_id'] = pk
    print trans.time
    return HttpResponse(template.render(context, request))

def del_trans(request, pk):
    trans = get_object_or_404(Transaction, trans_id=pk)
    try:
        trans.delete()
    except:
        return HttpResponseRedirect('/iti/fail')
    template = loader.get_template('iti/del_success.html')
    context = {}
    return HttpResponse(template.render(context, request))

webtest/iti/templates/iti/del_success.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:py="http://genshi.edgewall.org/">
<head>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Transaction deleted!</title>
<link rel="stylesheet" type="text/css" href="{% static "iti/fail.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/bootstrap.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/headerandfooter.css"%}" />
<script src="{% static "iti/jquery.min.js" %}"></script>
<script src="{% static "iti/bootstrap.min.js" %}"></script>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    	<div class="header-content">
        	<div class="navbar-brand">
            	Success!			
            </div>
        </div>
    </div>
</nav>

<div class="container">
	<p class="success"> Transaction deleted! </p>
</div>

<div id="footer" class="container">
	<nav class="navbar navbar-default navbar-fixed-bottom">
    	<div class="navbar-inner navbar-content-center">
        	<div class="container">
        	<button type="button" class="btnsend" onclick="{location.href='/iti/send'}"> Send Money </button>
			<button type="button" class="btnhistory" onclick="{location.href='/iti/history'}"> Transaction History </button>
            </div>
        </div>
    </nav>
</div>

</body>
</html>

webtest/iti/templates/iti/fail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:py="http://genshi.edgewall.org/">
<head>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Failed</title>
<link rel="stylesheet" type="text/css" href="{% static "iti/fail.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/bootstrap.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/headerandfooter.css"%}" />
<script src="{% static "iti/jquery.min.js" %}"></script>
<script src="{% static "iti/bootstrap.min.js" %}"></script>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    	<div class="header-content">
        	<div class="navbar-brand">
            	Failed			
            </div>
        </div>
    </div>
</nav>

<div class="container">
	<p class="success"> Sorry, the action is failed.</p>
</div>

<div id="footer" class="container">
	<nav class="navbar navbar-default navbar-fixed-bottom">
    	<div class="navbar-inner navbar-content-center">
        	<div class="container">
        	<button type="button" class="btnsend" onclick="{location.href='send'}"> Send Money </button>
			<button type="button" class="btnhistory" onclick="{location.href='history'}"> Transaction History </button>
            </div>
        </div>
    </nav>
</div>

</body>
</html>

webtest/iti/templates/iti/history.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:py="http://genshi.edgewall.org/">
<head>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Transaction History</title>
<link rel="stylesheet" type="text/css" href="{% static "iti/history.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/bootstrap.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/headerandfooter.css"%}" />
<script src="{% static "iti/jquery.min.js" %}"></script>
<script src="{% static "iti/bootstrap.min.js" %}"></script>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    	<div class="header-content">
        	<div class="navbar-brand">
            	Transaction History			
            </div>
        </div>
    </div>
</nav>

<div class="container">
	<table class="table1">
    	<tr class="tr1">
			<th class="th1"><h3><strong>Time</strong></h3></th>
			<th class="th2"><h3><strong>To</strong></h3></th>
			<th class="th3"><h3><strong>Amount</strong></h3></th>
		</tr>
        {% for aa in trans%}
        
        <tr class="tr2">
        	
        	<td class="td1"><a href="/iti/history/{{aa.3}}">{{aa.0}}</a></td>
			<td class="td2"><a href="/iti/history/{{aa.3}}">{{aa.1}}</a></td>
			<td class="td3"><a href="/iti/history/{{aa.3}}">{{aa.2}}</a></td> 
                   	
        </tr>
        
        {% endfor %}
    </table>
</div>

<div id="footer" class="container">
	<nav class="navbar navbar-default navbar-fixed-bottom">
    	<div class="navbar-inner navbar-content-center">
        	<div class="container">
        	<button type="button" class="btnback" onclick="{location.href='/iti'}"> Back </button>
            </div>
        </div>
    </nav>
</div>

</body>
</html>

webtest/iti/templates/iti/index.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:py="http://genshi.edgewall.org/">
<head>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Initial</title>
<link rel="stylesheet" type="text/css" href="{% static "iti/index.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/bootstrap.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/headerandfooter.css"%}" />
<script src="{% static "iti/jquery.min.js" %}"></script>
<script src="{% static "iti/bootstrap.min.js" %}"></script>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    	<div class="header-content">
        	<div class="navbar-brand">
            	What are we doing?			
            </div>
        </div>
    </div>
</nav>

<div class="container">
	<button type="button" onclick="{location.href='send'}" class="btnsend">Send Money</button>
    <button type="button" onclick="{location.href='history'}" class="btnview">View Transaction History</button>
</div>

<div id="footer" class="container">
	<nav class="navbar navbar-default navbar-fixed-bottom">
    	<div class="navbar-inner navbar-content-center">
        </div>
    </nav>
</div>
</body>
</html>

webtest/iti/templates/iti/send.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:py="http://genshi.edgewall.org/">
<head>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Send Money</title>
<link rel="stylesheet" type="text/css" href="{% static "iti/send.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/bootstrap.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/headerandfooter.css"%}" />
<script src="{% static "iti/jquery.min.js" %}"></script>
<script src="{% static "iti/bootstrap.min.js" %}"></script>
<script>
function formreset() {
    document.getElementById("sendform").reset();
}
</script>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    	<div class="header-content">
        	<div class="navbar-brand">
            	Send Money			
            </div>
        </div>
    </div>
</nav>
<form method="post" action="{% url 'iti:success' %}" id="sendform">
{% csrf_token %}
  <div class="container">
    <div class="mainframe">
      <label for="email" class="email1 label">to:</label>
      <input type="email" placeholder="Example: xxx@xxx" id="email" name="email" class="email1" required/>
    </div>
    <div class="mainframe">
      <label for="amount" class="amount label" id="amount_label">Amount: $</label>
      <input type="number" placeholder="0.00" id="amount" name="amount" class="amount" required/>

      <select name="cashtype" class="cashtype" id="currency" required>
      {% for aa in currency %}
      	<option value ="{{aa}}" id="{{aa}}">{{aa}}</option>
      {% endfor %}
      </select>
    </div>
    <div class="mainframe2">
      <p>Message (optional):</p>
      <textarea type="text" id="message" rows="2" name="message" class="text"></textarea>
    </div>
    <p class="text1">What's this payment for?</p>
    <div class="mainframe3" required>
      <label for="person" class="label1">I'm sending money to family and friends</label>
      <input type="radio" name="reason" value="person" id="person" class="radio1" checked="checked"/>
      <hr />
      <label for="service" class="label2">I'm paying goods or services</label>
      <input type="radio" name="reason" value="service" id="service"  class="radio2"/>
    </div>
  </div>


<div id="footer" class="container">
	<nav class="navbar navbar-default navbar-fixed-bottom">
    	<div class="navbar-inner navbar-content-center">
        	<div class="container">
        	<button type="button" class="btnclear" onclick="formreset()"> Clear </button>
			<input type="submit" value="Next" class="btnnext" id="submit1" />
            </div>
        </div>
    </nav>
</div>
</form>
<script src="{% static "iti/send.js" %}"></script>
</body>
</html>

webtest/iti/templates/iti/success.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:py="http://genshi.edgewall.org/">
<head>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Success</title>
<link rel="stylesheet" type="text/css" href="{% static "iti/success.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/bootstrap.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/headerandfooter.css"%}" />
<script src="{% static "iti/jquery.min.js" %}"></script>
<script src="{% static "iti/bootstrap.min.js" %}"></script>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    	<div class="header-content">
        	<div class="navbar-brand">
            	Send Money			
            </div>
        </div>
    </div>
</nav>

<div class="container">
	<p class="success"> You have sent {{amount}} to {{email}}.</p>
    <div class="tick">
    	<img src="{% static "iti/image/tick.png" %}"/>
    </div>
</div>

<div id="footer" class="container">
	<nav class="navbar navbar-default navbar-fixed-bottom">
    	<div class="navbar-inner navbar-content-center">
        	<div class="container">
        	<button type="button" class="btnsend" onclick="{location.href='/iti/send'}"> Send Money </button>
			<button type="button" class="btnhistory" onclick="{location.href='/iti/history'}"> Transaction History </button>
            </div>
        </div>
    </nav>
</div>

</body>
</html>

webtest/iti/templates/iti/transaction.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:py="http://genshi.edgewall.org/">
<head>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Transaction to {{email}}</title>
<link rel="stylesheet" type="text/css" href="{% static "iti/transaction.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/bootstrap.css"%}" />
<link rel="stylesheet" type="text/css" href="{% static "iti/headerandfooter.css"%}" />
<script src="{% static "iti/jquery.min.js" %}"></script>
<script src="{% static "iti/bootstrap.min.js" %}"></script>
</head>

<body>
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    	<div class="header-content">
        	<div class="navbar-brand">
            	Transaction to {{email}}			
            </div>
        </div>
    </div>
</nav>

<div class="container">
	<p class="success"> You have sent {{amount}} to {{email}} on {{date}}.</p>
    <button type="button" onclick="{location.href='/iti/del/{{trans_id}}'}" class="btndel">Delete</button>
</div>

<div id="footer" class="container">
	<nav class="navbar navbar-default navbar-fixed-bottom">
    	<div class="navbar-inner navbar-content-center">
        	<div class="container">
        	<button type="button" class="btnback" onclick="history.back()"> Back </button>
			<button type="button" class="btnhome" onclick="{location.href='/iti'}"> Home </button>
            </div>
        </div>
    </nav>
</div>

</body>
</html>