webtest/digest/urls.py
from django.conf.urls import url

from . import views

app_name = 'digest'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^result$', views.result, name='result'),
    url(r'^empty$', views.empty, name='empty'),
]

##if settings.DEBUG and settings.STATIC_ROOT:
##    urlpatterns += static(settings.STATIC_URL,
##                          document_root=settings.STATIC_ROOT)

webtest/iti/urls.py
from django.conf.urls import url

from . import views

app_name = 'iti'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^send$', views.send, name='send'),
    url(r'^success$', views.success, name='success'),
    url(r'^history$', views.history, name='history'),
    url(r'^fail$', views.fail, name='fail'),
    url(r'^history/(?P<pk>[0-9]+)', views.transaction, name='transaction'),
    url(r'^del/(?P<pk>[0-9]+)', views.del_trans, name='delete transaction'),
]

webtest/webtest/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^rest/', include('rest.urls')),
    url(r'^digest/', include('digest.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^iti/', include('iti.urls')),
    url(r'^admin/', admin.site.urls),
]

webtest/digest/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible  # only if you need to support Python 2
class EnzymeList(models.Model):
    id = models.IntegerField(primary_key=True, blank=True, null=False)  # AutoField?
    name = models.TextField(blank=True, null=True)  # This field type is a guess.
    amount = models.TextField(blank=True, null=True)  # This field type is a guess.
    digest = models.TextField(blank=True, null=True)  # This field type is a guess.
    start_pos = models.TextField(blank=True, null=True)  # This field type is a guess.
    def __str__(self):
        return self.name
    class Meta:
        managed = False
        db_table = 'enzyme_list'

webtest/digest/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.core.urlresolvers import reverse
from django.views import generic

from .models import EnzymeList
from .Digest import Digest

def index(request):
    enzyme_list = EnzymeList.objects.using('digestdb').order_by('id')
    
    template = loader.get_template('digest/digest.html')
    context = {
        'enzyme_list': enzyme_list,
    }
    return HttpResponse(template.render(context, request))

def result(request):
    enzyme_selected_id = []
    enzyme_selected_name = []
    for i in request.POST:
        if i.encode().startswith('check'):
            enzyme_selected_id.append(int(request.POST[i])-1)

    #if no enzyme selected, return an error page named 'empty'
    if not enzyme_selected_id:
        return HttpResponseRedirect('/digest/empty')
    enzyme_selected_id.sort()
    
    #parsing format of enzyme_list, for previous written Digest class
    #   since this is only a transplant work
    enzyme_list_db = EnzymeList.objects.using('digestdb').all().order_by('id')
    enzyme_list = []
    for i in enzyme_list_db:
        if i.id in enzyme_selected_id:
            enzyme_selected_name.append(i.name)
        enzyme_list.append([i.name, i.amount, i.digest, i.start_pos])
    seq = request.POST['sequence'].encode()
    digest = Digest(enzyme_list)
    digest.selectenzyme(enzyme_selected_id)
    digest_result = digest.digest(seq)

    #output data format
    result_formatted = []
    result_count = []
    for i in digest_result:
        if not i:
            temp = 'None.'
            result_count.append(0)
        else:
            result_count.append(len(i))
            temp = ' '.join(i)
        result_formatted.append(temp)
    output = zip(enzyme_selected_name,result_formatted,result_count)

    seq1 = request.POST['sequence'].encode()
    seq1 = digest.seq_formation(seq1)
    seq_len = len(seq1)
    sequence = digest.output_seq(seq1)
    if not digest.is_legal(seq1):
        sequence = "Please input a protein sequence in text or FASTA formation."
        self.output = []
        seq_len = " N/A "
    print sequence
    #load template and output the page
    template = loader.get_template('digest/result.html')
    context = {
        'digest_result' : output,
        'sequence' : sequence,
        'seq_length' : seq_len
    }
    return HttpResponse(template.render(context, request))

def empty(self, cancel = False):
    return HttpResponse("""<h1>Please select at least one enzyme.</h1>
            <a href="/digest">Back</a>""")

webtest/digest/templates/digest/digest.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:py="http://genshi.edgewall.org/">
<head>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Protein Digest</title>
<link rel="stylesheet" type="text/css" href="{% static "digest/digest.css"%}" />
<script src="{% static "digest/jquery.min.js" %}"></script>
<script>
$(function () {
$("#selectall").click(function () {
        $("#chkenzyme :checkbox").each(function () {
            this.checked = true;
			})
		});
$("#selectnone").click(function () {
        $("#chkenzyme :checkbox").attr("checked", false);  
    });  
$("#selectinvert").click(function () {
        $("#chkenzyme :checkbox").each(function () {
            this.checked = !this.checked;
         })
	});
});
</script>
</head>

<body>
<p id="ptitle"> Protein Digest </p>
<form method="post" action="{% url 'digest:result' %}">
{% csrf_token %}
  <p id="form1">
    <textarea id="sequence" name="sequence" onpropertychange="if(this.scrollHeight>6) this.style.posHeight=this.scrollHeight+3" onmouseover="this.focus();if(value==defaultValue) this.select();" onclick="if(value==defaultValue){value='';this.style.color='#778C79'}"          onBlur="if(!value){value=defaultValue;this.style.color='#778C79'}" >Please input a protein sequence in FASTA formation.</textarea>
    <br />
    <br />
    <button id="selectall" type="button" class="btn">Select All</button>&nbsp;
    <button id="selectnone" type="button" class="btn">Select None</button>&nbsp;
    <button id="selectinvert" type="button" class="btn">Reverse</button>&nbsp;
    <div>
    <div class="list1">
{% if enzyme_list %}
    <ul id="chkenzyme">
    {% for enzyme in enzyme_list %}
        <li><input name="check{{enzyme.id}}" type="checkbox" value="{{enzyme.id}}" checked="true" class="checkbox1"/>
    	<label class="list1_content">{{enzyme.name}}</label></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
    </div>
    </div>
       </p>
    
    
    <input name="submit" type="submit" value="Submit" class="btn" />
    


  
</form>

</body>
</html>

webtest/digest/templates/digest/index.html
{% if enzyme_list %}
    <ul>
    {% for enzyme in enzyme_list %}
        <li>{{ enzyme.name }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

webtest/digest/templates/digest/result.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xmlns:py="http://genshi.edgewall.org/">

<head>
{% load staticfiles %}
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="{% static "digest/result.css"%}" />
<title>Result</title>
</head>

<body>
<p id="ptitle">
Result
</p>

<p id="p02">The sequence to investigate:</p>
<p id="p01">Length:&nbsp;{{seq_length}}aa</p>
<br/>
<div style="table-3" id="table-3">
<table>
{% for bb in sequence %}
<tr>

{% for cc in bb %}
<td align = "right" > {{cc}} </td>
{% endfor %}

</tr>
{% endfor %}

</table>
</div>
<div style="table-4" id="table-4">
<table>
<tr>
<td><h3><strong>Name</strong></h3></td>
<td><h3><strong>No.</strong></h3></td>
<td><h3><strong>Positions</strong></h3></td>
</tr>
{% for aa in digest_result%}
<tr>
<td><strong>{{aa.0}}:</strong></td>
<td>{{aa.2}}</td>
<td>{{aa.1}}</td>


</tr>
{% endfor %}

<br />

<br />
</table>
</div>
<br />
<a href="/digest" id = "back">
Back
</a>
</body>
</html>